# Generated by Django 4.1 on 2022-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blogs/47457024971233/",
                verbose_name="main image",
            ),
        ),
    ]
