# Generated by Django 4.1 on 2022-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blogs/8473526273259/",
                verbose_name="main image",
            ),
        ),
    ]
