# Generated by Django 4.1 on 2022-08-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="corresponding_page",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("all", "All"),
                    ("forex", "Forex"),
                    ("stocks", "Stocks"),
                    ("commodities", "Commodities"),
                    ("indices", "Indices"),
                    ("etf", "ETF"),
                    ("crypto", "Crypto"),
                ],
                default="all",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blogs/19171360766722/",
                verbose_name="main image",
            ),
        ),
    ]
