# Generated by Django 4.1 on 2022-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CenterSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_slide_content", models.TextField()),
                ("second_slide_content", models.TextField()),
                ("third_slide_content", models.TextField()),
            ],
            options={
                "verbose_name": "Centralized Slide",
                "verbose_name_plural": "Centralized Slides",
            },
        ),
    ]
