# Generated by Django 4.1 on 2022-08-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_centerslider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centerslider",
            name="first_slide_content",
            field=models.TextField(
                help_text="Search box will be appended to the end of this content"
            ),
        ),
    ]
