# Generated by Django 4.1 on 2022-08-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_alter_centerslider_first_slide_content"),
    ]

    operations = [
        migrations.DeleteModel(name="CenterSlider",),
    ]
