# Generated by Django 4.1 on 2022-08-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_alter_centerslider_image_alter_centerslider_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerslider",
            name="image_mobile",
            field=models.ImageField(
                blank=True, null=True, upload_to="slide/36716387155755/"
            ),
        ),
        migrations.AlterField(
            model_name="centerslider",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="slide/92388082054943/"
            ),
        ),
    ]
