# Generated by Django 4.1 on 2022-08-26 14:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="corresponding_page",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("all", "All"),
                    ("forex", "Forex"),
                    ("stocks", "Stocks"),
                    ("commodities", "Commodities"),
                    ("indices", "Indices"),
                    ("etf", "ETF"),
                    ("crypto", "Crypto"),
                ],
                default="all",
                max_length=255,
            ),
        ),
    ]
