# Generated by Django 4.1 on 2022-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_manager_corresponding_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="managers/52278810429264/",
                verbose_name="manager image",
            ),
        ),
        migrations.AddField(
            model_name="manager",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="manager image alt"
            ),
        ),
    ]
