# Generated by Django 4.1 on 2022-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_manager_image_manager_image_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="managers/41309726008274/",
                verbose_name="manager image",
            ),
        ),
    ]
