# Generated by Django 4.1 on 2022-08-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_alter_manager_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="managers/45294804434648/",
                verbose_name="manager image",
            ),
        ),
    ]
